baseURL = 'https://daily-blog-inky.vercel.app'
languageCode = 'en-us'
title = 'Amodh'

paginate = 4

[params]
  description = "The fastest blog"
  dateFormat = "Jan 2, 2006"

[taxonomies]
  category = "categories"
  author = "authors"